version: '3.9'

services:
  web:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000 && python manage.py tailwind start"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"