# Generated by Django 4.2.2 on 2023-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('published', 'Published')], default='pending', max_length=9),
        ),
    ]
